### ISSUE TITLE
打扰一下，能否自定义工具栏？Excuse me，Can you customize the toolbar？

### ISSUE THREAD

**Issue by shaoting0730** [xrb21/flutter-html-editor#20]
Excuse me，Can you customize the toolbar？
![image](https://user-images.githubusercontent.com/14305431/96835043-96e12a00-1475-11eb-9aa8-d2baa90f561f.png)
need 123 , do not need 456 tools.

**Comment by shaoting0730** [comment]
再加入国际化配置。
You need to add internationalization configuration again，please。

**Comment by blue492** [comment]
flutter_summernote plugin did a customize for the toolbar here:
https://pub.dev/packages/flutter_summernote

But all summernote plugins developers should be updated to work in iOS
https://pub.dev/packages?q=summernote

**Comment by shaoting0730** [comment]
good job,thank you very much.
