### ISSUE TITLE
Is there anyway to turn off the constant log coming out of the local_server.dart module?

### ISSUE THREAD

**Issue by Corruption13** [xrb21/flutter-html-editor#42]
It keeps displaying the print() text over the android studio console every second. Shouldn't the log be disabled by default? It makes simple print debugging for the rest of the application in that screen impossible.

https://github.com/xrb21/flutter-html-editor/blob/master/lib/local_server.dart

**Comment by tneotia** [comment]
This package isn't being maintained much anymore - I forked it and have been maintaining/upgrading it at [html_editor_enhanced](https://github.com/tneotia/html-editor-enhanced). It doesn't use a local server so these logs aren't present (and performance is also better).

**Comment by Corruption13** [comment]
thank you, I will check it out!
