### ISSUE TITLE
dependency issue with flutter_html

### ISSUE THREAD

**Issue by akmichael** [xrb21/flutter-html-editor#43]
Hi,

when i use flutter_html ^2.0.0, this doesn't work. any workaround?

Depencies
  image_picker: ^0.6.4
  flutter_html: ^2.0.0
  html_editor: ^1.0.1

Because every version of html_editor depends on webview_flutter ^0.3.21 and flutter_html 2.0.0 depends on webview_flutter ^2.0.4, html_editor is incompatible with flutter_html 2.0.0.
And because no versions of flutter_html match >2.0.0 <3.0.0, html_editor is incompatible with flutter_html ^2.0.0.
So, because app depends on both flutter_html ^2.0.0 and html_editor ^1.0.1, version solving failed.
pub get failed (1; So, because app depends on both flutter_html ^2.0.0 and html_editor ^1.0.1, version solving failed.)

**Comment by tneotia** [comment]
This package isn't being maintained much anymore - I forked it and have been maintaining/upgrading it at [html_editor_enhanced](https://github.com/tneotia/html-editor-enhanced). This dependency conflict is not present in my package if you'd like to try it out.

**Comment by akmichael** [comment]
thanks @tneotia. i am using html_editor_enhanced. it solved my problem.
