### ISSUE TITLE
html_editor doesn't support WKWebView.

### ISSUE THREAD

**Issue by naeemAkee** [xrb21/flutter-html-editor#44]
I was trying to upload build, but I received that mail  from AppStore.

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

 I'm using
 ```
 html_editor: ^1.0.1
dependency_overrides:
  webview_flutter: ^2.0.8
```
 
please help me in that to resolve that issue

**Comment by tneotia** [comment]
This package isn't being maintained much anymore - I forked it and have been maintaining/upgrading it at [html_editor_enhanced](https://github.com/tneotia/html-editor-enhanced). I have an app on the App Store using html_editor_enhanced and I don't have this issue while submitting.

**Comment by naeemAkee** [comment]
Try not to use this library any more for iOS Apps.

**Comment by naeemAkee** [comment]
Try not to use this library any more for iOS Apps.
